// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCffLqMmj4rogf7GkP1yGRWD8xlitPM1CQ',
    appId: '1:692120913024:web:1c0e19d8f2cf0a36d85265',
    messagingSenderId: '692120913024',
    projectId: 'shoewardrobe-22db3',
    authDomain: 'shoewardrobe-22db3.firebaseapp.com',
    storageBucket: 'shoewardrobe-22db3.firebasestorage.app',
    measurementId: 'G-Y5GYYCRTJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKPfUocF7W5-UymL_3K2cgLjM5CIurKsM',
    appId: '1:692120913024:android:fa6c24bdd4b38adbd85265',
    messagingSenderId: '692120913024',
    projectId: 'shoewardrobe-22db3',
    storageBucket: 'shoewardrobe-22db3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCImVd5AQb7T1ncGU1TA0WTy0maJsvUZbc',
    appId: '1:692120913024:ios:d025a5410d98edced85265',
    messagingSenderId: '692120913024',
    projectId: 'shoewardrobe-22db3',
    storageBucket: 'shoewardrobe-22db3.firebasestorage.app',
    iosBundleId: 'com.example.shoeWardrobeAdmin',
  );
}
